### ISSUE TITLE
GH action: add github action for lint, build and test

### ISSUE THREAD

**Issue by zdtsw** [rogerwelin/cfnctl#3]
**Describe the solution you'd like**
Would be good to have go testing done in GH action for better quality gate.

**Describe alternatives you've considered**
Think for lint can use Action from https://github.com/golangci/golangci-lint (.golangci.yaml)
But for testing, not sure any available Action for golang, probably need to write simple jobs.

**Comment by rogerwelin** [comment]
Yep, definitely a must have. will fix
